org.gradle.jvmargs = -Xmx2G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# <build> will be replaced with the build number
version = 1.0.<build>

authors = simibubi, Pepper, zelophed
contributors = IThundxr, Jozufozu, Snownee, gamez7, tterrag, Grimmauld, TropheusJ
