# Gradle
org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

# Project
mod_version = 1.0
maven_group = net.createmod.ponder

# Common
minecraft_version = 1.21.11
parchment_minecraft_version = 1.21.11
parchment_version = none
flywheel_minecraft_version = 1.21.1
flywheel_version = 1.0.4

# This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
# https://projects.neoforged.net/neoforged/neoform
neo_form_version = 1.21.11-20251209.172050

# NeoForge
# https://neoforged.net/
mdg_version = 2.0.123
neo_version = 21.11.0-beta
flywheel_version_range = [1.0.0,2.0)

# Fabric
# https://fabricmc.net/develop/
loom_version = 1.13.+
fabric_version = 0.139.4+1.21.11
fabric_loader_version = 0.18.2
forgeconfigapiport_version = 21.10.1

# Mod options
mod_id = ponder
mod_name = Ponder
mod_author = simibubi, Pepper, zelophed
mod_credit = Special Thanks to IThundxr, Jozufozu, Snownee, gamez7, tterrag and Grimmauld
mod_homepage = https://github.com/Creators-of-Create/Ponder
mod_source = https://github.com/Creators-of-Create/Ponder
mod_issues = https://github.com/Creators-of-Create/Ponder/issues
mod_description = Visual in-Game Documentation
mod_license = MIT
