plugins {
    id "net.neoforged.moddev.legacyforge" version "${mdg_version}"
}

apply from: "../gradle/property_helper.gradle"

archivesBaseName = "${mod_name}-Common-${minecraft_version}"

legacyForge {
    mcpVersion = minecraft_version

    accessTransformers.from(file('src/main/resources/META-INF/ponder.accesstransformer.cfg').absolutePath)

    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = parchment_version
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.4"

    implementation "com.electronwill.night-config:core:3.6.5"
    implementation "com.electronwill.night-config:toml:3.6.5"
    compileOnly "net.minecraftforge:forgeconfigapiport-fabric:3.2.3" //source: https://github.com/Fuzss/forgeconfigapiport-fabric

    compileOnly "dev.engine-room.flywheel:flywheel-common-mojmap-api-${minecraft_version}:${flywheel_version}"

}

java {
    withJavadocJar()
    withSourcesJar()
}

// -- MAVEN PUBLISHING --
project.publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId project.archivesBaseName

            from components.java
            /*// Base mod archive.
            artifact jar

            // Adds the sources as an artifact.
            artifact project.sourcesJar {
                 classifier "sources"
            }

            // Adds the javadocs as an artifact.
            artifact project.javadocJar {
                classifier "javadoc"
            }*/
        }
    }

    repositories {
        maven {
            // Sets maven credentials if they are provided. This is generally
            // only used for external/remote uploads.
            if (project.hasProperty("mavenUsername") && project.hasProperty("mavenPassword")) {

                credentials {

                    username findProperty("mavenUsername")
                    password findProperty("mavenPassword")
                }
            }

            url getDefaultString("mavenURL", "undefined", true)
        }
    }
}
